name: Deploy to Firebase

on:
   push:
    branches:
      - master

jobs:
  build:
    name: Building and distributing app
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.1.1
        
      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with: 
           java-version: '1.8'
           distribution: 'adopt'
        
      - name: Build with Gradle
        run: ./gradlew build

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle command - assembleDebug
        run: ./gradlew assembleDebug
    
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: crypto.apk
          path: app/build/outputs/apk/debug/app-debug.apk
          
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk   
